version: 2.1

orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  lint-infras:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install cfn lint
          command: |
            pip install cfn-lint
      - run:
          name: Validate CloudFormation template
          command: |
            return 1
            cfn-lint infras/infras.yml

  deploy-infras:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          no_output_timeout: 30m
          command: |
            aws cloudformation deploy \
            --template-file infras/infras.yml \
            --parameter-overrides $(jq -r '.[] | [.ParameterKey, .ParameterValue] | "\(.[0])=\(.[1])"' ./infras/infras-params.json) \
            --stack-name << parameters.stack-name >> \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

workflows:
  capstone:
    jobs:
      - lint-infras
      - deploy-infras:
          stack-name: capstone-demo
          requires:
            - lint-infras